name: show a full fledged Terraform CI/CD pipeline with GH action

env:
  working-directory: ./atul/Example


on:
  push:   
    branches: ["main", "master"]
  pull_request: 
    branches: ["main", "master"]

  workflow_dispatch:  


jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: us-east-1
      
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2 

      - name: Terraform fmt
        id: fmt
        run: terraform fmt 
      
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{env.working-directory}}

      - name: Terraform Validate
        id: validate
        run: terraform validate 
        working-directory: ${{env.working-directory}}

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ${{env.working-directory}}
      
      - name: Terrafom Plan status
        if: steps.plan.outcome == 'failure'
        run: echo somthing error place check the code once!!!!!!

      - name: Terraform apply
        id: apply
        if: steps.plan.outcome != 'failure'
        run: terraform apply -auto-approve
        working-directory: ${{env.working-directory}}

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ${{env.working-directory}}





# name: Terraform actions

# on:
#  push: 
#   branches: ["main","master"]

#  workflow_dispatch:

# jobs:
#   terraform:
#     name: 'Terraform'
#     runs-on: ubuntu-latest
 
#     env:
#       AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
#       AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
#       AWS_DEFAULT_REGION: us-east-1
#       working_folder:  ./atul/Example
      
#     defaults:
#       run:  
#         working-directory: ${{ env.working_folder }}

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
     
#     - name: Terraform Init
#       run: terraform init

#     - name: Terraform Validate
#       run: terraform validate

#     - name: Terraform Plan
#       run: terraform plan 
      
#     - name: Terraform Apply
#       run: terraform apply -auto-approve 

#     - name: Terraform Destroy
#       run: terraform destroy -auto-approve 



